name: qgreenland
platforms:
  - linux-64
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.11

  ################################################################
  # Imported dependencies and extensions (and related typestubs) #
  ################################################################

  - anytree ~=2.8
  - click ~=8.3
  - fiona ~=1.10
  - gdal ~=3.10
  - humanize ~=2.6
  - luigi ~=3.0
  # setuptools <80 is required for luigi, which needs to be able to `import
  # pkg_resources`. This goes away with setuptools 80+
  # TODO: remove if luigi ever updates
  - setuptools <80.0.0
  - pydantic ~=1.10
  - qgis ~=3.44.0
  - requests ~=2.25
  - types-requests ~=2.25
  - netCDF4 ~=1.7.2
  - pandas ~=2.3
  # required for `pandas` to read excel files.
  - openpyxl ~=3.0
  - pyyaml ~=5.4
  - types-pyyaml ~=5.4
  - funcy ~=1.16
  - markdown ~=3.3
  - types-markdown ~=3.3
  - earthaccess ~=0.16.0


  #############################
  # Non-imported dependencies #
  #############################

  # documentation dependencies
  # TODO: Upgrade sphinx ones sphinx-rtd-theme supports 7
  # - sphinx ~=7.2.2
  - sphinx ~=6.2.1
  - latexmk ~=4.55
  - myst-parser ~=2.0.0
  - sphinx-click ~=3.0.1
  - sphinx-rtd-theme ~=1.2.2
  - sphinxext-rediraffe ~=0.2.7
  - autodoc-pydantic ~=1.9.0
  # TODO: What does this do? Do we need it?
  # - sphinx-autodoc-typehints ~=1.12.0
  # SEE PIP DEPENDENCIES FOR MORE

  # task-runners
  - invoke ~=2.2

  # test-runners
  - pytest
  - pytest-cov

  # linting
  - pre-commit

  # typechecking
  # NOTE: later mypy versions (>=1.18) do not seem to play well with pydantic
  # mypy extension.
  - mypy ~=1.17.0

  # other utilities
  - bump-my-version
  - conda-lock
  - ipython
  - ipdb

  - pip

  # Pip dependencies could be imported or non-imported :(
  - pip:
    - sphinx-selective-exclude ~=1.0
