name: qgreenland
platforms:
  - linux-64
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.10

  ################################################################
  # Imported dependencies and extensions (and related typestubs) #
  ################################################################

  - anytree ~=2.8.0
  # HACK: Click 8.1.4 introduces typechecking issues. Remove restriction after
  # fixes are merged.
  # https://github.com/pallets/click/issues/2558
  # https://github.com/pallets/click/pull/2562/files
  - click ~=8.0, <8.1.4
  - fiona ~=1.8.13
  - gdal ~=3.6.0
  - humanize ~=2.6.0
  - luigi ~=3.0.2
  - pydantic ~=1.10
  - qgis ~=3.28.6
  - requests ~=2.25.0
  - types-requests ~=2.25.0
  - netCDF4 ~=1.5
  - pandas ~=1.3
  # required for `pandas` to read excel files.
  - openpyxl ~=3.0
  - pyyaml ~=5.4.1
  - types-pyyaml ~=5.4.1
  - funcy ~=1.16
  - markdown ~=3.3.6
  - types-markdown ~=3.3.6


  #############################
  # Non-imported dependencies #
  #############################

  # documentation dependencies
  - sphinx ~=4.3.1
  - latexmk ~=4.55
  - myst-parser ~=0.15.2
  - sphinx-click ~=3.0.1
  # TODO: What does this do? Do we need it?
  # - sphinx-autodoc-typehints ~=1.12.0
  # SEE PIP DEPENDENCIES FOR MORE

  # task-runners
  - invoke ~=1.4.0

  # test-runners
  - pytest ~=6.2
  - pytest-cov ~=2.12

  # linting
  - pre-commit

  # typechecking
  - mypy ~=1.2.0

  # other utilities
  - conda-lock
  - ipython
  - ipdb

  - pip

  # Pip dependencies could be imported or non-imported :(
  - pip:
    - sphinx-rtd-theme ~=1.0.0
    - autodoc-pydantic ~=1.5.1
    - sphinx-selective-exclude ~=1.0.3
    # TODO: Put this in conda-forge!
    - bump-my-version ~=0.9.2
