# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: doc/conf.py
  # There doesn't seem to be a way to turn on nitpicky mode.
  # This is equivalent to `-W --keep-going`.
  fail_on_warning: True

formats:
  - pdf
  - epub

python:
  install:
    - requirements: doc/requirements.txt
