name: qgreenland
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.10

  ################################################################
  # Imported dependencies and extensions (and related typestubs) #
  ################################################################

  - anytree ~=2.8.0
  - click ~=8.0
  - fiona ~=1.8.13
  - gdal ~=3.6.0
  - humanize ~=2.6.0
  - luigi ~=3.0.2
  - pydantic ~=1.8
  - qgis ~=3.28.6
  - requests ~=2.25.0
  - types-requests ~=2.25.0
  - netCDF4 ~=1.5
  - pandas ~=1.3
  # required for `pandas` to read excel files.
  - openpyxl ~=3.0
  - pyyaml ~=5.4.1
  - types-pyyaml ~=5.4.1
  - funcy ~=1.16
  - markdown ~=3.3.6
  - types-markdown ~=3.3.6


  #############################
  # Non-imported dependencies #
  #############################

  # documentation dependencies
  - sphinx ~=4.3.1
  - latexmk ~=4.55
  - myst-parser ~=0.15.2
  - sphinx-click ~=3.0.1
    # TODO: What does this do? Do we need it?
    # - sphinx-autodoc-typehints ~=1.12.0
    # SEE PIP DEPENDENCIES FOR MORE

  # task-runners
  - invoke ~=1.4.0

  # test-runners
  - pytest ~=6.2
  - pytest-cov ~=2.12

  # static analysis
  - flake8 ~=3.8.3
  - flake8-bugbear ~=21.9.2
  - flake8-comprehensions ~=3.2.2
  - flake8-docstrings ~=1.5.0
  - flake8-import-order ~=0.18.1
  - flake8-quotes ~=2.1.1
  - pep8-naming ~=0.9.1
  - vulture ~=1.0
  - shellcheck ~=0.7.1
    # SEE PIP DEPENDENCIES FOR MORE

  # typechecking
  - mypy ~=1.2.0

  # other utilities
  - bump2version
  - ipython
  - ipdb
  - pip
  - black ~=22.0
  - isort ~=5.0


  # Pip dependencies could be imported or non-imported :(
  - pip:
    - flake8-debugger ~=3.2
    - flake8-use-fstring ~=1.0
    - sphinx-rtd-theme ~=1.0.0
    - autodoc-pydantic ~=1.5.1
    - sphinx-selective-exclude ~=1.0.3
