classes:
  - nsidc_miniconda

nsidc_miniconda::install:
  /opt/miniconda:
    version: '4.3.27'
    owner: vagrant
    group: vagrant
    build: true
    config:
      location: /home/vagrant
      channels:
        anaconda_nsidc_main: false
        anaconda_nsidc_dev: false
        conda_forge: true
