forge "https://forgeapi.puppetlabs.com"

# Module for access to NSIDC Enterprise storage
mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git",
  :ref => 'latest'

# Module for creating NSIDC Jenkins servers
mod "nsidc/nsidc_jenkins",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git",
  :ref => 'latest'

mod "nsidc/nsidc_miniconda",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-miniconda.git",
  :ref => "v7.0.0"
