- id: latlon
  assets:
    - id: lat_0_5_deg
      type: repo
      filename: 'latitudes_0_5_degree.geojson'
    - id: lat_0_25_deg
      type: repo
      filename: 'latitudes_0_25_degree.geojson'
    - id: lat_1_deg
      type: repo
      filename: 'latitudes_1_degree.geojson'
    - id: lat_2_deg
      type: repo
      filename: 'latitudes_2_degree.geojson'
    - id: lat_5_deg
      type: repo
      filename: 'latitudes_5_degree.geojson'
    - id: lat_10_deg
      type: repo
      filename: 'latitudes_10_degree.geojson'
    - id: lat_15_deg
      type: repo
      filename: 'latitudes_15_degree.geojson'
    - id: lat_20_deg
      type: repo
      filename: 'latitudes_20_degree.geojson'
    - id: lat_30_deg
      type: repo
      filename: 'latitudes_30_degree.geojson'
    - id: lon_0_5_deg
      type: repo
      filename: 'longitudes_0_5_degree.geojson'
    - id: lon_1_deg
      type: repo
      filename: 'longitudes_1_degree.geojson'
    - id: lon_2_deg
      type: repo
      filename: 'longitudes_2_degree.geojson'
    - id: lon_3_deg
      type: repo
      filename: 'longitudes_3_degree.geojson'
    - id: lon_5_deg
      type: repo
      filename: 'longitudes_5_degree.geojson'
    - id: lon_10_deg
      type: repo
      filename: 'longitudes_10_degree.geojson'
    - id: lon_15_deg
      type: repo
      filename: 'longitudes_15_degree.geojson'
    - id: lon_20_deg
      type: repo
      filename: 'longitudes_20_degree.geojson'
    - id: lon_30_deg
      type: repo
      filename: 'longitudes_30_degree.geojson'
    - id: lon_45_deg
      type: repo
      filename: 'longitudes_45_degree.geojson'
    - id: lon_90_deg
      type: repo
      filename: 'longitudes_90_degree.geojson'
  metadata:
    title: 'Latitude and Longitude Lines'
    abstract: 'Latitude and Longitude Lines'
    citation:
      text: 'Generated by QGreenland.'
      url: ''
