version: 2

setup: &setup
  docker:
    - image: continuumio/miniconda3:4.10.3
  environment:
    # QGIS complains when setting up an QgsApplicatoin if `QT_QPA_PLATFORM` is not
    # set to `offscreen`:
    #     qt.qpa.xcb: could not connect to display
    #     qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even
    #     though it was found.
    #     This application failed to start because no Qt
    #     platform plugin could be initialized. Reinstalling the application
    #     may fix this problem.
    #
    #     Available platform plugins are: eglfs, minimal, minimalegl,
    #     offscreen, vnc, webgl, xcb.
    #
    #     Fatal Python error: Aborted
    QT_QPA_PLATFORM: offscreen
  working_directory: ~/qgreenland

jobs:
  test:
    <<: *setup
    steps:
      - checkout
      - run:
          name: 'Apt install libgl1-mesa-glx'
          command: |
            # Install libgl1-mesa-glx. Import errors occur otherwise.
            # See: https://app.circleci.com/jobs/github/nsidc/qgreenland/72/parallel-runs/0/steps/0-102
            apt-get update && apt-get install -y libgl1-mesa-glx
      - run:
          name: 'Run all tests (lint, config validation, etc.)'
          command: |
            conda env create --quiet -f environment-lock.yml
            conda init bash
            /bin/bash --login -c "conda activate qgreenland && inv test.ci"

  trigger_build:
    <<: *setup
    steps:
      - run:
          name: 'Trigger Jenkins to build production package'
          command: |
            JENKINS_URL="http://ci.qgreenland.apps.nsidc.org"
            REF="${CIRCLE_TAG}"
            JOB_NAME="qgreenland_C3_Production_Build_QGreenland_Package"

            REQ_URL="${JENKINS_URL}/job/${JOB_NAME}/buildWithParameters?ref=${REF}&delay=5sec"
            wget "$REQ_URL"

workflows:
  version: 2

  # For commits on any branch, only run tests.
  # For tags vX.Y.Z*, run tests then trigger a Jenkins build.
  test_and_sometimes_trigger_build:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      - trigger_build:
          requires:
            - test 
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
            branches:
              ignore: /.*/
