name: "🐞 Bug"
description: |
  Suggest a dataset for inclusion to QGreenland.
title: "[Bug]: "
labels: ["Bug"]
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "Issue description"
      description: |
        What symptoms are you observing? Please include screenshots if
        possible.
    validations:
      required: true

  - type: "textarea"
    id: "system-info"
    attributes:
      label: "System information"
      description: |
        Please provide information about the system on which you're
        experiencing the error.
      placeholder: |
        * Operating system:
        * Operating system version:
        * QGIS version:
        * QGreenland version:
    validations:
      required: true
