name: "📡 Dataset proposal"
description: >-
  Suggest a dataset for inclusion to QGreenland.
title: "[Dataset]: "
labels: ["Dataset: proposal"]
body:

  - type: "markdown"
    attributes:
      value: >-
        Thanks for taking the time to propose a dataset to QGreenland. Please
        keep in mind that the _QGreenland Core_ package must maintain a
        reasonable file size, so we have to be selective.

        The best thing you can do to prepare for future development is to
        ingest your data into DataONE.

        Please also keep in mind that it may take on the order of months for
        our team to respond to your proposal!

  - type: "input"
    id: "dataset-url"
    attributes:
      label: "Dataset URL"
      description: "Please provide a landing page URL for your proposed dataset."
    validations:
      required: false

  - type: "textarea"
    id: "rationale"
    attributes:
      label: "Rationale"
      description: >-
        Please explain how you feel this dataset would benefit QGreenland. For
        example, does it provide data from a scientific discipline or
        environmental aspect that's currently not covered?
    validations:
      required: true
