name: qgreenland-cmd
platforms:
  - linux-64
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gdal ~=3.12.0
  - libgdal-netcdf ~=3.12
  - netCDF4 ~=1.7.2
  - unzip ~=6.0
  - p7zip ~=16.02
  - wget ~=1.21
  - pandas ~=3.0
  - geopandas ~=1.1
