#!/usr/bin/env bash
# This script is a deployment script tailored to NSIDC's deployment
# environment. It needs to be genericized!
set -euo pipefail

source VERSION.env

# Restart the luigi container, leaving the webserver up
docker-compose rm -sf luigi
docker system prune -af
docker-compose up --build -d
