kwargs:
  - segment_max_distance

steps:
  - type: 'command'
    args:
      - 'ogr2ogr'
      - '-lco'
      - 'ENCODING=UTF-8'
      - '-clipdst'
      - '{assets_dir}/latitude_shape_40_degrees.geojson'
        # - '-cliplayer'
        # - 'latitude_shape_40_degrees'
      - '-segmentize'
      - '{segment_max_distance}'
      - '{output_file}'
      - '{input_file}'
