name: "Test and (if tag) build"

on:
  push:
      branches:
        - "*"
      tags:
        - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:


# Default to bash in login mode; key to activating conda environment
# https://github.com/mamba-org/provision-with-micromamba#IMPORTANT
defaults:
  run:
    shell: "bash -l {0}"


jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"

      - name: "Apt install libgl1-mesa-glx"
        run: |
          # Install libgl1-mesa-glx. Import errors occur otherwise.
          # See: https://app.circleci.com/jobs/github/nsidc/qgreenland/72/parallel-runs/0/steps/0-102
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx

      # Rename lock file; mamba expects files ending in `-lock.yml` to have a different format :(
      # https://github.com/mamba-org/mamba/issues/1209#issuecomment-1447546266
      - name: "HACK: Rename lockfile"
        run: "mv environment-lock.yml environment-ci.yml"

      - name: "Install Conda environment"
        uses: "mamba-org/setup-micromamba@v1.4.1"
        with:
          environment-file: "environment-ci.yml"
          cache-environment: true

      - name: "Run tests"
        run: "inv test.ci"
        env:
          # QGIS complains when setting up an QgsApplicatoin if `QT_QPA_PLATFORM` is not
          # set to `offscreen`:
          #     qt.qpa.xcb: could not connect to display
          #     qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even
          #     though it was found.
          #     This application failed to start because no Qt
          #     platform plugin could be initialized. Reinstalling the application
          #     may fix this problem.
          #
          #     Available platform plugins are: eglfs, minimal, minimalegl,
          #     offscreen, vnc, webgl, xcb.
          #
          #     Fatal Python error: Aborted
          QT_QPA_PLATFORM: offscreen


  build:
    runs-on: "ubuntu-latest"
    needs: ["test"]
    if: "github.ref_type == 'tag'"
    steps:
      - name: "Trigger Jenkins to build QGreenland Core"
        run: |
          JOB_NAME="qgreenland_C3_Production_Build_QGreenland_Package"
          JOB_URL="${{ secrets.JENKINS_URL }}/job/${JOB_NAME}"
          JOB_BUILD_URL="${JOB_URL}/buildWithParameters?ref=${{ github.ref_name }}&delay=5sec"

          wget "$JOB_BUILD_URL"
